### ISSUE TITLE
Test Juno accessing Docker  with Julia v1.0

### ISSUE THREAD

**Issue by jlperla** [ubcecon/computing_and_datascience#77]
While you don't technically need the full Jupyter here, I think you should do this after getting #73 up and running.

See 
http://docs.junolab.org/latest/man/faq.html#Connecting-to-a-Julia-session-in-a-(local)-Docker-container-1

I think that Juno is now working with Julia 1.0?  If so, can you see if it works to access a local docker installation, with the typical juno features (e.g. built-in REPL, `<Ctrl-Enter>` on code to run, etc.)

If it doesn't work, we can file bugs with the Juno team, and also submit PRs for the documentation.

Also, if there is a small change in the features that might make it a more useful workflow (e.g. storing the ports in the config file to make it easier to just execute the last docker?  Integration with Atom Docker, etc.) then think about them.  We may be able to spend a little time adding to the project to make things easier.

**Comment by jlperla** [comment]
Does it work well? Did you try it with v1.0.

**Comment by jasminefish000** [comment]
I tried it with the docker image of Julia 1.0. It worked fine. I had a bit problem testing the connection on a windows machine, (no instruction was given at any formal format). But if follow the above instruction, it should work. 

Actually, we can even have the docker image mounted to a local directory on the machine, so that I can easily access the local files.

**Comment by jasminefish000** [comment]
Sometimes I have the connection refused issue, this helped.
`docker run -it -p 8888:8888 jupyter/minimal-notebook`
